server:
  port: 8000

spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      routes:
        - id: auth               #?? ???? ?? ???
          uri: lb://AUTHSERVICE  #?? ???? ??
          predicates:            #???? ?? ?? /auth/**? ???? ?? ?? ???? ?? ??
            Path=/auth/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
