server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8001
          predicates:
            Path=/auth-service/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
