server:
  port: 8761

spring:
  application:
    name: eurekaService

eureka:
  client:
    register-with-eureka: false # ??? ?? ??? ???? registry? ???? ??
    fetch-registry: false # registy? ?? ??? ???? ??? ??
